{
    'name': 'Sales Representative Manager',
    'version': '18.0',
    'depends': ['mail', 'sale', 'base', 'account', 'auth_signup', 'base_address_extended', 'stock', 'product'],
    'author': 'Mohammad Haitham Salman',
    'category': 'Sales/CRM',
    'description': 'Adds employee_ids field to CRM Team and custom view',
    'data': [

        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sales_rep_profile_sequence.xml',
        'views/route_line_views.xml',
        'views/auth_signup_templates_email.xml',
        'views/sales_rep_profile_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/res_currency_views.xml',
        'views/location_map_views.xml',
        'report/invoice_report_template.xml',
        'report/report_picking_batch.xml',
        'report/stock_picking_batch_report_views.xml',
        'views/report_invoice.xml',
        'report/report_stockpicking_operations.xml',
        'views/cashvan_invoice_log_views.xml',
        'views/loyalty_program_views.xml',
        'wizard/import.xml',
        'wizard/import_with_ref_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sales_rep_manager/static/src/js/location_map/location_map.js',
            'sales_rep_manager/static/src/xml/location_map.xml',
        ],
    },

    'installable': True,
    'application': False,
    'auto_install': False,
}
